---
- name: lamp stack install on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: apache install on ubuntu
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
    - name: php install on ubuntu
      ansible.builtin.apt:
        name: php
        state: present
    - name: create group
      ansible.builtin.group:
        name: suresh
        state: present
    - name: domain directory create
      ansible.builtin.file:
        name: suresh
        path: /var/www/
        recurse: true
        owner: suresh
        group: suresh
        state: directory