---
- name: lamp stack install on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: apache install on ubuntu
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
    - name: php install on ubuntu
      ansible.builtin.apt:
        name: php
        state: present
    - name: libapache2-mod-php install on ubuntu
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: present
    - name: create group
      ansible.builtin.group:
        name: kola
        state: present
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www/suresh
        state: directory
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: /var/www/suresh
        recurse: yes
        owner: kola
        group: kola
        state: directory
    - name: create conf file
      ansible.builtin.copy:
        src: suresh.conf
        dest: /etc/apache2/sites-available/suresh.conf
        owner: kola
        group: kola
    - name: enable new site
      ansible.builtin.command: "sudo /usr/sbin/a2ensite suresh.conf"
    - name: dsable default apache server
      ansible.builtin.command: "sudo /usr/sbin/a2ensite 000-default"
    - name: reload apache2
      ansible.builtin.systemd:
        name: apache2
        state: reloaded
    - name: create index file
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/suresh/index.html
        owner: kola
        group: kola