---
- name: lamp stack install on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: apache install on ubuntu
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
    - name: php install on ubuntu
      ansible.builtin.apt:
        name: php
        state: present
    - name: create group
      ansible.builtin.group:
        name: suresh
        state: present
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www/kola
        state: directory
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: /var/www/kola
        recurse: yes
        owner: suresh
        group: suresh
        state: directory
    - name: create conf file
      ansible.builtin.copy:
        src: kola.conf
        dest: /etc/apache2/sites-available/kola.conf
        owner: suresh
        group: suresh
    - name: enable new site
      ansible.builtin.command: "/usr/sbin/a2ensite kola"
    - name: dsable default apache server
      ansible.builtin.command: "/usr/sbin/a2ensite 000-default"
    - name: reload apache2
      ansible.builtin.systemd:
        name: apache2
        state: reloaded
    - name: create index file
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/suresh/index.html
        owner: suresh
        group: suresh