---
- name: tomcat install on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: openjdk-11-jdk install
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present
    - name: add tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: add tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: true
        home: /opt/tomcat
        shell: /bin/false
        group: tomcat
        state: present